name: cinescope
description: Application universitaire de découverte de films.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.5
  flutter: '>=3.47.6'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.9
  go_router: ^18.0.2
  http: ^1.6.0
  shadcn_ui: ^0.57.1
  flutter_riverpod: ^3.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/cat_mascot.png
